plugins {
    id 'java'
    id 'java-library'
    id 'maven-publish'
    id 'xyz.wagyourtail.unimined' version '1.4.26-kappa'
}

version = mod_version
group = root_package
base { archivesName = mod_id }

java {
    toolchain { languageVersion = JavaLanguageVersion.of(25) }
    withSourcesJar()
}

configurations {
    modCompileOnly
    compileOnly.extendsFrom(modCompileOnly)
    modRuntimeOnly
    runtimeOnly.extendsFrom(modRuntimeOnly)
}

unimined.minecraft {
    version '1.12.2'
    mappings { mcp('stable', '39-1.12') }
    cleanroom {
        loader '0.6.1-alpha'
        runs.all {
            args += ['--username', minecraft_username]
            systemProperty('fml.noSplash', 'true')
            if (is_coremod.toBoolean()) systemProperty('fml.coreMods.load', coremod_plugin_class_name)
        }
    }
    defaultRemapJar = false
    remap(tasks.named('jar').get())
    mods {
        remap(configurations.modCompileOnly)
        remap(configurations.modRuntimeOnly)
    }
}

repositories {
    mavenCentral()
    mavenLocal()
    maven { url = 'https://jitpack.io' }
    maven { url = 'https://curse.cleanroommc.com' }
}

dependencies {
    compileOnly 'com.cleanroommc:sponge-mixin:0.20.13+mixin.0.8.7'
    compileOnly 'com.cleanroommc:lwjglx:1.0.0'
    modCompileOnly project(':stellarapi')
    modRuntimeOnly files('../StellarAPI/build/libs/stellarapi-1.12.2-0.5.2.2.jar')
}

processResources {
    def metadata = [version: project.version, mcversion: '1.12.2']
    inputs.properties(metadata)
    filesMatching('mcmod.info') { expand(metadata) }
}

compileJava {
    sourceCompatibility = targetCompatibility = JavaVersion.VERSION_25
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

jar {
    archiveClassifier = 'dev'
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    manifest {
        attributes(
                'ModType': 'CRL',
                'FMLCorePlugin': coremod_plugin_class_name,
                'FMLCorePluginContainsFMLMod': true,
                'Fabric-Loom-Mixin-Remap-Type': 'mixin'
        )
    }
    finalizedBy tasks.named('remapJar')
}
